apiVersion: v1
kind: Service
metadata:
  name: postgres-movie
spec:
  selector:
    app: postgres-movie
  ports:
    - port: 5432
      targetPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-review
spec:
  selector:
    app: postgres-review
  ports:
    - port: 5432
      targetPort: 5432